### ISSUE TITLE
怎么运行

### ISSUE THREAD

**Issue by JaccePon** [heisedebaise/tephra#1]
你好，大牛，请问项目怎么运行？？
![wbias1 dp qj0g x7j92 76](https://cloud.githubusercontent.com/assets/18736284/21714051/076550c6-d438-11e6-977b-00484f435d40.png)

已经用clean install -Dmaven.test.skip=true命令打包成功了。打包之后是存放在这里的吗：
![ppe_y79f uvll0m4 6i 4x4](https://cloud.githubusercontent.com/assets/18736284/21714138/6798416a-d438-11e6-8e01-1b248a58e055.png)

这个要怎么运行？看你的文档好像是打包成功就可以运行了的，但是访问http://localhost:8080/hello?name=Tephra 并不行，大神方便留下QQ或邮箱交流一下吗？

**Comment by JaccePon** [comment]
{"code":9999,"message":"系统在运行过程中发生不可意料的异常！"}
我用tomcat来部署啦，之后出现了上面那个错误。这个是什么原因？还有就是在部署的时候会有如下这个异常信息出现：

警告: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tephra.bean.factory' defined in URL [jar:file:/E:/tomcat6.0.3/apache-tomcat-6.0.39/webapps/ROOT/WEB-INF/lib/tephra-core-1.0.0-RELEASE.jar!/org/lpw/tephra/bean/BeanFactory.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tephra.bean.container': Unsatisfied dependency expressed through field 'refreshedListeners'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tephra.ctrl.http.ws.helper': Failed to introspect bean class [org.lpw.tephra.ctrl.http.ws.WsHelperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: javax/websocket/Session
一月 06, 2017 8:22:42 下午 org.springframework.web.context.ContextLoader initWebApplicationContext
严重: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tephra.bean.factory' defined in URL [jar:file:/E:/tomcat6.0.3/apache-tomcat-6.0.39/webapps/ROOT/WEB-INF/lib/tephra-core-1.0.0-RELEASE.jar!/org/lpw/tephra/bean/BeanFactory.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tephra.bean.container': Unsatisfied dependency expressed through field 'refreshedListeners'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tephra.ctrl.http.ws.helper': Failed to introspect bean class [org.lpw.tephra.ctrl.http.ws.WsHelperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: javax/websocket/Session
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4210)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4709)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1429)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:297)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:631)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:568)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:295)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1471)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1312)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1404)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:832)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tephra.bean.container': Unsatisfied dependency expressed through field 'refreshedListeners'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tephra.ctrl.http.ws.helper': Failed to introspect bean class [org.lpw.tephra.ctrl.http.ws.WsHelperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: javax/websocket/Session
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1225)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:552)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:220)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1016)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1093)
	at org.lpw.tephra.bean.BeanFactory.setApplicationContext(BeanFactory.java:84)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:121)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:97)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1581)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	... 55 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tephra.ctrl.http.ws.helper': Failed to introspect bean class [org.lpw.tephra.ctrl.http.ws.WsHelperImpl] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: javax/websocket/Session
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:269)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1079)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1052)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1297)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1263)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1169)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1094)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$OptionalDependencyFactory.createOptionalDependency(DefaultListableBeanFactory.java:1583)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1051)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	... 74 more
Caused by: java.lang.NoClassDefFoundError: javax/websocket/Session
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:247)
	... 90 more
Caused by: java.lang.ClassNotFoundException: javax.websocket.Session
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
	... 97 more



这个包为什么会没有？？？

**Comment by JaccePon** [comment]
我在pom文件中加了 javax.websocket的包，上面的异常没有了，tomcat可以启动了，但是启动完成之后还是会弹出页面显示：

{"code":9999,"message":"系统在运行过程中发生不可意料的异常！"}


而后台打印出来的是：


INFO  2017-01-06 20:55:14 org.lpw.tephra.ctrl.http.ServiceHelperImpl 部署项目路径[]。
一月 06, 2017 8:55:14 下午 org.springframework.web.context.ContextLoader initWebApplicationContext
信息: Root WebApplicationContext: initialization completed in 8044 ms
[2017-01-06 08:55:14,972] Artifact tephra-web:war exploded: Artifact is deployed successfully
[2017-01-06 08:55:14,972] Artifact tephra-web:war exploded: Deploy took 9,255 milliseconds
WARN  2017-01-06 20:55:15 org.lpw.tephra.ctrl.DispatcherImpl 无法获得请求[/]的处理服务！
WARN  2017-01-06 20:55:15 org.lpw.tephra.ctrl.DispatcherImpl 无法获得请求[/]的处理服务！
一月 06, 2017 8:55:15 下午 org.apache.catalina.startup.HostConfig deployDirectory
信息: Deploying web application directory manager
WARN  2017-01-06 20:55:16 org.lpw.tephra.ctrl.DispatcherImpl 无法获得请求[/]的处理服务！


不明白是为什么这样，访问http://localhost:8080/hello?name=Tephra，可以成功，但是访问
http://localhost:8080/hi?name=Tephra  ，就不行啦，后台有异常：


The name was interpreted by this TemplateLoader: FileTemplateLoader(baseDir="D:\IDEAProjects\tephra\tephra-web\target\tephra-web\WEB-INF\ftl", canonicalBasePath="D:\IDEAProjects\tephra\tephra-web\target\tephra-web\WEB-INF\ftl\").
    freemarker.template.Configuration.getTemplate(Configuration.java:2485)
    freemarker.template.Configuration.getTemplate(Configuration.java:2287)
    org.lpw.tephra.freemarker.FreemarkerImpl.process(FreemarkerImpl.java:54)
    org.lpw.tephra.ctrl.template.freemarker.TemplateImpl.process(TemplateImpl.java:44)
    org.lpw.tephra.ctrl.context.ResponseImpl.write(ResponseImpl.java:68)
    org.lpw.tephra.ctrl.DispatcherImpl.execute(DispatcherImpl.java:110)
    org.lpw.tephra.ctrl.DispatcherImpl.execute(DispatcherImpl.java:94)
    org.lpw.tephra.ctrl.http.ServiceHelperImpl.service(ServiceHelperImpl.java:126)
    org.lpw.tephra.ctrl.http.ServiceFilter.doFilter(ServiceFilter.java:29)
    org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    org.lpw.tephra.ctrl.http.SecurityFilter.filter(SecurityFilter.java:35)
    org.lpw.tephra.ctrl.http.SecurityFilter.doFilter(SecurityFilter.java:30)
    org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    java.lang.Thread.run(Thread.java:745)
解析模版[hi]时发生异常！


再然后我就进行了如下的修改：

![izxcsxtmmv0 ot 0 _iin 2](https://cloud.githubusercontent.com/assets/18736284/21718828/e25ac9ba-d454-11e6-8665-e5e20ec8ee32.png)



猜想是不是这样对应的。结果还是不行。。。求解

**Comment by JaccePon** [comment]
猜想好像是对的，只是位置不对，哈哈。
但是已启动完成就是出现：

{"code":9999,"message":"系统在运行过程中发生不可意料的异常！"}

请问这个是什么原因？

**Comment by heisedebaise** [comment]
可以把后台的日志贴出来看看吗？9999错误都会有异常日志输出的。


________________________________
发件人: JaccePon <notifications@github.com>
发送时间: 2017年1月6日 13:30
收件人: heisedebaise/tephra
抄送: Subscribed
主题: Re: [heisedebaise/tephra] 怎么运行 (#1)


猜想好像是对的，只是位置不对，哈哈。
但是已启动完成就是出现：

{"code":9999,"message":"系统在运行过程中发生不可意料的异常！"}

请问这个是什么原因？

―

**Comment by heisedebaise** [comment]
少websocket那个应该是你tomcat版本太低导致的，建议使用8+。
“无法获得请求[/]的处理服务”这个错误是因为你没有配置“／”服务。
“http://localhost:8080/hi?name=Tephra”是因为模板文件需要放在／web-inf／ftl，当然你也可以修改core.tephra.config指定其他位置。

**Comment by JaccePon** [comment]
上面的问题我都解决了，是路径不对。还有一些是jar包的问题。

还有个问题是，页面模板用的是freemarker吗？这个模板没用过，看了一些文档。我下面的这样的取值方式对吗？但是页面上取不出值。后台也报错： The following has evaluated to null or missing：name

![z dx um540d2y9ong5vgca](https://cloud.githubusercontent.com/assets/18736284/21840270/870aab7c-d817-11e6-90bc-1d5990a34278.png)

![c3s8a who h mxwb evzgv](https://cloud.githubusercontent.com/assets/18736284/21840356/0f7a19ca-d818-11e6-9207-ac1941a6d03e.png)

**Comment by JaccePon** [comment]
上面的第一个截图不对，是这个：

![7pf e rgtq6dro sto1h](https://cloud.githubusercontent.com/assets/18736284/21840447/8da01d18-d818-11e6-86b0-f506eb2cc6a5.png)

**Comment by heisedebaise** [comment]
返回的参数会被添加到data节点，你可以使用${data.name}获得name值。可参考https://github.com/heisedebaise/tephra/blob/master/tephra-ctrl/doc/template.md。

**Comment by heisedebaise** [comment]
模板文件中可通过${converter}获得util.Converter实例，用于对数据进行转化操作。
${message}可获得util.Message，用于输出资源信息。
